---
# key-gen.yml

- name: Create an EC2 key
  ec2_key:
      name: "{{ key_name }}"
      region: "{{ region }}"
  register: ec2_key
    
- name: save private key
  copy: content="{{ ec2_key.key.private_key }}" dest="{{key_folder}}/{{key_name}}.pem" mode=0600
  when: ec2_key.changed
