---
    
 webservers_security_groups:
   - sg_name: webserver_sg
     sg_description: Security goup for generic web servers
     sg_rules:
       - proto: tcp
         from_port: 22
         to_port: 22
         cidr_ip: 0.0.0.0/0
       - proto: tcp
         from_port: 80
         to_port: 80
         cidr_ip: 0.0.0.0/0
         