# Securit group  data
---

- name: WebServer | Create webserver Security Group
  local_action:
     module: ec2_group
     name: "{{ item.sg_name }}"
     description: "{{ item.sg_description }}"
     region: "{{ region }}" 
     vpc_id: "{{ vpc_id }}" 
     state: present
     rules: "{{ item.sg_rules }}"
  with_items: webservers_security_groups
  register: web_sg
  
- name: WebServer | Tag the WEB Security Group with a name
  local_action:
     module: ec2_tag
     resource: "{{ item.group_id}}"
     region: "{{ region }}"
     state: present
     tags:
       Name: "{{ vpc.name }}-{{ item.item.sg_name }}"
  with_items: web_sg.results  
