---

- name: "VPC | Creating an AWS VPC in {{ vpc.region }} region"
  local_action: 
     module: ec2_vpc
     region: "{{ vpc.region }}"
     state: present
     cidr_block: "{{ vpc.cidr }}"
     resource_tags: { "Name":"{{ vpc.name }}" }
     subnets: "{{ subnets }}" 
     internet_gateway: yes
     route_tables: "{{ public_subnet_rt }}"
  register: newvpc

- name: VPC | Write vpc id to file inside the vars directory
  shell: echo "{{ newvpc.vpc_id }}" > "{{ vpc.name }}-vpc-info.yml"
  args:
     chdir: "{{tmp_folder}}"
     

- name: VPC | Write public and private subnets id to files inside the vars directory  
  shell: echo "{{ item.id }}" > "{{ item.resource_tags.Name }}.yml"
  args:
     chdir: "{{tmp_folder}}"
  with_items: newvpc.subnets

- name: VPC | Set the public and private subnet id as facts
  set_fact:
     vpc_id:                 "{{ lookup('file',  tmp_folder + '/' + vpc.name + '-vpc-info.yml') }}"
     public_subnet_1: "{{ lookup('file',  tmp_folder + '/' + subnet_public_1_name  +'.yml') }}"
     public_subnet_2: "{{ lookup('file',  tmp_folder + '/' + subnet_public_2_name  +'.yml') }}"
     private_subnet:   "{{ lookup('file',  tmp_folder + '/' + subnet_private_1_name +'.yml') }}"
     
  
- name: VPC | save vpc info to the aws assets file 
  shell: echo "{{ newvpc }}" > "vpc-dynamic-info.yml" && echo "{{ vpc }}" > "vpc-static-info.yml"
  args:
     chdir: "{{ assets_folder }}"  
 
